#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   whiptail --msgbox "This script must be run as root" 8 78
   exit 1
fi

USER=pi
#branch=dev
config=/home/$USER/.config
wireless_config=/etc/hostapd/hostapd.conf
#wireless_interface=`iw dev | awk '$1=="Interface"{print $2}'`
availableInterfaces=`ip --oneline link show up | grep -v "lo" | grep -v "eth0" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1`
current_SSID=`cat $wireless_config | grep "^ssid="`
current_interface=`cat $wireless_config | grep "^interface="`
current_channel=`cat $wireless_config | grep "^channel="`
current_password=`cat $wireless_config | grep "^wpa_passphrase="`
source /opt/Radio-VNC/funtions.sh

if [ -t 0 ] ; then
  screen_size=$(stty size)
else
  screen_size="24 80"
fi

printf -v rows '%d' "${screen_size%% *}"
printf -v columns '%d' "${screen_size##* }"

# Divide by two so the dialogs take up half of the screen, which looks nice.
r=$(( rows / 2 ))
c=$(( columns / 2 ))
#r=20
#c=70


SSID=`whiptail --title "Radio-VNC Wi-FI config" --passwordbox "Enter SSID:" "${r}" "${c}" 3>&1 1>&2 2>&3`

channel_choice(){
    Channel=`whiptail --title "Radio-VNC Wi-FI config" --passwordbox "Enter AP Channel:" "${r}" "${c}" 3>&1 1>&2 2>&3`
}
channel_choice

if [ $Channel != 1...14 ]; then
  whiptail --title "Radio-VNC Wi-Fi config" --msgbox "Channel value must be a number between 1 and 14" "${r}" "${c}"
  channel_choice
fi

chooseInterface

if (whiptail --title "Radio-VNC Wi-Fi Config" --defaultno --yesno "Would you like to make the AP Hidden?" "${r}" "${c}"); then
  Hidden=TRUE
else
  Hiddden=False
fi

AP_Password(){
   Password=$(whiptail --title "Radio-VNC Wi-FI config" --passwordbox "Enter AP Password:" "${r}" "${c}" 3>&1 1>&2 2>&3)
   Password_check=$(whiptail --title "Radio-VNC Wi-FI config" --passwordbox "Re-enter AP Password:" "${r}" "${c}" 3>&1 1>&2 2>&3)
}

AP_Password

if [ "$Password" != "$Password_check" ]; then
  whiptail --title "Radio-VNC Wi-Fi Config" --msgbox "Passwords do not match, please try again" "${r}" "${c}"
  AP_Password
fi

sed -i "s/$current_interface/interface=$Radio_VNC_INTERFACE/" $wireless_config
sed -i "s/$current_SSID/ssid=$SSID/" $wireless_config
sed -i "s/$current_channel/channel="$channel"/" $wireless_config
sed -i "s/$current_password/wpa_passphrase="$Password"/" $wireless_config

systemctl restart hostapd
whiptail --title "Radio-VNC Wi-Fi config" --msgbox "Wi-fi config set" "${r}" "${c}"
